package com.jecp.sysmanage.model;
// Generated 2017-12-12 14:56:14 by Hibernate Tools 5.2.6.Final

/**
 * TawSystemUser generated by hbm2java
 */
public class TawSystemUser implements java.io.Serializable {

	private String id;
	private String userid;
	private String username;
	private Long deptid;
	private String deptname;
	private String password;
	private String mobile;
	private String accountLocked;
	private String failCount;
	private String weixinid;
	private Boolean external;
	private Boolean deleted;
	private Integer seq;
	private String remark;

	public TawSystemUser() {
	}

	public TawSystemUser(String id, String userid) {
		this.id = id;
		this.userid = userid;
	}

	public TawSystemUser(String id, String userid, String username, Long deptid, String deptname, String password,
			String mobile, String accountLocked, String failCount, String weixinid, Boolean external, Boolean deleted,
			Integer seq, String remark) {
		this.id = id;
		this.userid = userid;
		this.username = username;
		this.deptid = deptid;
		this.deptname = deptname;
		this.password = password;
		this.mobile = mobile;
		this.accountLocked = accountLocked;
		this.failCount = failCount;
		this.weixinid = weixinid;
		this.external = external;
		this.deleted = deleted;
		this.seq = seq;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Long getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Long deptid) {
		this.deptid = deptid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAccountLocked() {
		return this.accountLocked;
	}

	public void setAccountLocked(String accountLocked) {
		this.accountLocked = accountLocked;
	}

	public String getFailCount() {
		return this.failCount;
	}

	public void setFailCount(String failCount) {
		this.failCount = failCount;
	}

	public String getWeixinid() {
		return this.weixinid;
	}

	public void setWeixinid(String weixinid) {
		this.weixinid = weixinid;
	}

	public Boolean getExternal() {
		return this.external;
	}

	public void setExternal(Boolean external) {
		this.external = external;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
